name: Supermarket Image

env:
  IMAGE_NAME: springboot-k3s-supermarket

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: supermarket
    steps:
    - name: Get current datetime
      id: datetime
      run: |
        # Store current date and time in a variable
        echo "timestamp=$(date +'%y%m%d')" >> $GITHUB_OUTPUT
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Set VERSION environment variable
      run: |
        echo "VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV
    - name: Build with Maven
      run: mvn -DskipTests=true -B package --file pom.xml
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      with:
        platforms: linux/amd64,linux/arm64
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push Docker images
      uses: docker/build-push-action@v4.1.1
      with:
        context: .
        push: true
        platforms: linux/amd64,linux/arm64
        tags: |
         ${{ github.actor }}/${{ env.IMAGE_NAME }}:latest
         ${{ github.actor }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}
